version: '3'
services:
  web: &application
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-dev
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - ./dockerfiles/.env.dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ~/.ssh/docker:/root/.ssh
    ports:
      - 13002:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13308:3306
    volumes:
      - db:/var/lib/mysql
      - ./dockerfiles/mysql_conf:/etc/mysql/conf.d

volumes:
  db:
  bundle:

